// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"time"
)

type SimulationRun struct {
	ID              int64     `json:"id"`
	CreatedAt       time.Time `json:"created_at" ts_transform:"new Date(__VALUE__)" ts_type:"Date"`
	ContextJson     string    `json:"context_json"`
	Action          string    `json:"action"`
	MatchedRuleID   *string   `json:"matched_rule_id"`
	MatchedRuleName *string   `json:"matched_rule_name"`
	ResultJson      string    `json:"result_json"`
	CreatedBy       *string   `json:"created_by"`
}
