// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const countSimulationRuns = `-- name: CountSimulationRuns :one
SELECT COUNT(*) FROM simulation_runs
`

func (q *Queries) CountSimulationRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSimulationRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSimulationRun = `-- name: DeleteSimulationRun :exec
DELETE FROM simulation_runs
WHERE id = ?
`

func (q *Queries) DeleteSimulationRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSimulationRun, id)
	return err
}

const getSimulationRun = `-- name: GetSimulationRun :one
SELECT id, created_at, context_json, "action", matched_rule_id, matched_rule_name, result_json, created_by FROM simulation_runs
WHERE id = ?
`

func (q *Queries) GetSimulationRun(ctx context.Context, id int64) (SimulationRun, error) {
	row := q.db.QueryRowContext(ctx, getSimulationRun, id)
	var i SimulationRun
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ContextJson,
		&i.Action,
		&i.MatchedRuleID,
		&i.MatchedRuleName,
		&i.ResultJson,
		&i.CreatedBy,
	)
	return i, err
}

const insertSimulationRun = `-- name: InsertSimulationRun :one
INSERT INTO simulation_runs (context_json, action, matched_rule_id, matched_rule_name, result_json, created_by)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at, context_json, "action", matched_rule_id, matched_rule_name, result_json, created_by
`

type InsertSimulationRunParams struct {
	ContextJson     string  `json:"context_json"`
	Action          string  `json:"action"`
	MatchedRuleID   *string `json:"matched_rule_id"`
	MatchedRuleName *string `json:"matched_rule_name"`
	ResultJson      string  `json:"result_json"`
	CreatedBy       *string `json:"created_by"`
}

func (q *Queries) InsertSimulationRun(ctx context.Context, arg InsertSimulationRunParams) (SimulationRun, error) {
	row := q.db.QueryRowContext(ctx, insertSimulationRun,
		arg.ContextJson,
		arg.Action,
		arg.MatchedRuleID,
		arg.MatchedRuleName,
		arg.ResultJson,
		arg.CreatedBy,
	)
	var i SimulationRun
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ContextJson,
		&i.Action,
		&i.MatchedRuleID,
		&i.MatchedRuleName,
		&i.ResultJson,
		&i.CreatedBy,
	)
	return i, err
}

const listSimulationRuns = `-- name: ListSimulationRuns :many
SELECT id, created_at, context_json, "action", matched_rule_id, matched_rule_name, result_json, created_by FROM simulation_runs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSimulationRunsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSimulationRuns(ctx context.Context, arg ListSimulationRunsParams) ([]SimulationRun, error) {
	rows, err := q.db.QueryContext(ctx, listSimulationRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimulationRun
	for rows.Next() {
		var i SimulationRun
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ContextJson,
			&i.Action,
			&i.MatchedRuleID,
			&i.MatchedRuleName,
			&i.ResultJson,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
