// apigen parses //api:route and //api:query comments from ui/app.go
// and generates daemon/routes.gen.go with typed gin handlers.
//
// Usage: go run ./apigen
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"text/template"
)

type route struct {
	Method    string
	GinPath   string
	RoutePath string // original path with {param} placeholders
	FuncName  string
	Params    []param
	Returns   []string
}

type param struct {
	GoName     string
	GoType     string
	Source     string // "path", "query", "body", "header"
	QueryKey   string // key in the query string (may differ from GoName)
	HeaderKey  string // HTTP header name (for "header" source)
	DefaultVal string // empty means required
}

// templateData is passed to the code generation template.
type templateData struct {
	Imports []string
	Routes  []route
}

var routeRe = regexp.MustCompile(`^//\s*api:route\s+(\w+)\s+(.+)$`)
var queryRe = regexp.MustCompile(`^//\s*api:query\s+(\w+)=\{(\w+)(?::([^}]*))?\}$`)
var headerRe = regexp.MustCompile(`^//\s*api:header\s+([A-Za-z0-9-]+)=\{(\w+)\}$`)
var pathParamRe = regexp.MustCompile(`\{(\w+)\}`)

func main() {
	_, thisFile, _, _ := runtime.Caller(0)
	root := filepath.Dir(filepath.Dir(thisFile))
	inputPath := filepath.Join(root, "internal", "server", "handlers.go")
	routesPath := filepath.Join(root, "internal", "server", "routes.gen.go")
	openapiPath := filepath.Join(root, "internal", "server", "openapi.gen.json")
	tsModelsPath := filepath.Join(root, "frontend", "src", "shared", "api", "models.gen.ts")
	tsClientPath := filepath.Join(root, "frontend", "src", "shared", "api", "api.gen.ts")

	routes, srcImports := parseSource(inputPath)
	imports := collectImports(routes, srcImports)

	data := templateData{Imports: imports, Routes: routes}

	var buf bytes.Buffer
	if err := routesTmpl.Execute(&buf, data); err != nil {
		log.Fatalf("template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile(routesPath, buf.Bytes(), 0644)
		log.Fatalf("gofmt failed (unformatted output written for debugging): %v", err)
	}

	if err := os.WriteFile(routesPath, formatted, 0644); err != nil {
		log.Fatalf("write %s: %v", routesPath, err)
	}

	specJSON, err := buildOpenAPISpecJSON(routes)
	if err != nil {
		log.Fatalf("marshal openapi: %v", err)
	}
	if err := os.WriteFile(openapiPath, specJSON, 0644); err != nil {
		log.Fatalf("write %s: %v", openapiPath, err)
	}

	fmt.Printf("generated %s (%d routes)\n", routesPath, len(routes))
	fmt.Printf("generated %s\n", openapiPath)

	if err := generateTS(routes, srcImports, tsModelsPath); err != nil {
		log.Fatalf("ts gen: %v", err)
	}
	fmt.Printf("generated %s\n", tsModelsPath)

	if err := generateTSClient(routes, tsClientPath); err != nil {
		log.Fatalf("ts client gen: %v", err)
	}
	fmt.Printf("generated %s\n", tsClientPath)
}

func collectImports(routes []route, srcImports map[string]string) []string {
	seen := map[string]bool{
		"github.com/gin-gonic/gin": true,
		"net/http":                 true,
	}

	needStrconv := false
	for _, r := range routes {
		for _, p := range r.Params {
			if p.GoType == "int64" && p.Source != "body" {
				needStrconv = true
			}
			addTypeImport(seen, srcImports, p.GoType)
		}
		// return types are not referenced in generated code (serialized as JSON)
	}
	if needStrconv {
		seen["strconv"] = true
	}

	imports := make([]string, 0, len(seen))
	for imp := range seen {
		imports = append(imports, imp)
	}
	return imports
}

func addTypeImport(seen map[string]bool, srcImports map[string]string, typeStr string) {
	t := strings.TrimPrefix(typeStr, "*")
	t = strings.TrimPrefix(t, "[]")
	t = strings.TrimPrefix(t, "*")
	pkg, _, ok := strings.Cut(t, ".")
	if !ok {
		return
	}
	if fullPath, ok := srcImports[pkg]; ok {
		seen[fullPath] = true
	}
}

var funcMap = template.FuncMap{
	"hasResult": func(r route) bool {
		return (len(r.Returns) > 1) || (len(r.Returns) == 1 && r.Returns[0] != "error")
	},
	"hasError": func(r route) bool {
		return len(r.Returns) > 0 && r.Returns[len(r.Returns)-1] == "error"
	},
	"callArgs": func(r route) string {
		args := make([]string, len(r.Params))
		for i, p := range r.Params {
			args[i] = p.GoName
		}
		return strings.Join(args, ", ")
	},
}

var routesTmpl = template.Must(template.New("routes").Funcs(funcMap).Parse(`// Code generated by apigen; DO NOT EDIT.
package server

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

func RegisterRoutes(r *gin.Engine, app *Server) {
{{- range .Routes}}
	r.{{.Method}}("{{.GinPath}}", func(c *gin.Context) {
		{{- range .Params}}
		{{- if eq .Source "path"}}
		{{- if eq .GoType "string"}}
		{{.GoName}} := c.Param("{{.GoName}}")
		{{- else if eq .GoType "int64"}}
		{{.GoName}}, err := strconv.ParseInt(c.Param("{{.GoName}}"), 10, 64)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid {{.GoName}}"})
			return
		}
		{{- end}}
		{{- else if eq .Source "query"}}
		{{- if eq .GoType "string"}}
		{{- if .DefaultVal}}
		{{.GoName}} := c.DefaultQuery("{{.QueryKey}}", "{{.DefaultVal}}")
		{{- else}}
		{{.GoName}} := c.Query("{{.QueryKey}}")
		{{- end}}
		{{- else if eq .GoType "int64"}}
		{{- if .DefaultVal}}
		{{.GoName}}, err := strconv.ParseInt(c.DefaultQuery("{{.QueryKey}}", "{{.DefaultVal}}"), 10, 64)
		{{- else}}
		{{.GoName}}, err := strconv.ParseInt(c.Query("{{.QueryKey}}"), 10, 64)
		{{- end}}
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid {{.QueryKey}}"})
			return
		}
		{{- end}}
		{{- else if eq .Source "header"}}
		{{.GoName}} := c.GetHeader("{{.HeaderKey}}")
		{{- else if eq .Source "body"}}
		var {{.GoName}} {{.GoType}}
		if err := c.ShouldBindJSON(&{{.GoName}}); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
		{{- end}}
		{{- end}}
		{{- $route := .}}
		{{- if and (hasResult $route) (hasError $route)}}
		result, err := app.{{.FuncName}}({{callArgs $route}})
		if err != nil {
			writeError(c, err)
			return
		}
		c.JSON(http.StatusOK, result)
		{{- else if hasError $route}}
		if err := app.{{.FuncName}}({{callArgs $route}}); err != nil {
			writeError(c, err)
			return
		}
		c.Status(http.StatusNoContent)
		{{- else if hasResult $route}}
		result := app.{{.FuncName}}({{callArgs $route}})
		c.JSON(http.StatusOK, result)
		{{- else}}
		app.{{.FuncName}}({{callArgs $route}})
		c.Status(http.StatusNoContent)
		{{- end}}
	})
{{end}}
}
`))

func parseSource(path string) ([]route, map[string]string) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	srcImports := map[string]string{}
	for _, imp := range f.Imports {
		p := strings.Trim(imp.Path.Value, `"`)
		name := filepath.Base(p)
		if imp.Name != nil {
			name = imp.Name.Name
		}
		srcImports[name] = p
	}

	var routes []route

	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || fn.Doc == nil {
			continue
		}

		method, routePath, queryParams, headerParams := parseComments(fn.Doc)
		if method == "" {
			continue
		}

		pathParams := extractPathParams(routePath)
		ginPath := pathParamRe.ReplaceAllString(routePath, ":$1")

		r := route{
			Method:    method,
			GinPath:   ginPath,
			RoutePath: routePath,
			FuncName:  fn.Name.Name,
			Returns:   extractReturns(fn),
		}

		if fn.Type.Params != nil {
			for _, field := range fn.Type.Params.List {
				goType := exprToString(field.Type)
				for _, name := range field.Names {
					p := classifyParam(name.Name, goType, pathParams, queryParams, headerParams)
					r.Params = append(r.Params, p)
				}
			}
		}

		routes = append(routes, r)
	}

	return routes, srcImports
}

// parseComments extracts the route method, path, query, and header params from a doc block.
func parseComments(doc *ast.CommentGroup) (string, string, map[string]param, map[string]param) {
	var method, routePath string
	queryParams := map[string]param{}
	headerParams := map[string]param{}

	for _, c := range doc.List {
		if m := routeRe.FindStringSubmatch(c.Text); m != nil {
			method = m[1]
			routePath = m[2]
			continue
		}
		if m := queryRe.FindStringSubmatch(c.Text); m != nil {
			goName := m[2]
			queryParams[goName] = param{
				QueryKey:   m[1],
				DefaultVal: m[3],
			}
			continue
		}
		if m := headerRe.FindStringSubmatch(c.Text); m != nil {
			goName := m[2]
			headerParams[goName] = param{
				HeaderKey: m[1],
			}
		}
	}

	return method, routePath, queryParams, headerParams
}

// extractPathParams returns the set of param names found as {name} in the path.
func extractPathParams(routePath string) map[string]bool {
	params := map[string]bool{}
	for _, m := range pathParamRe.FindAllStringSubmatch(routePath, -1) {
		params[m[1]] = true
	}
	return params
}

// classifyParam assigns a source (path/query/header/body) to a function parameter.
func classifyParam(name, goType string, pathParams map[string]bool, queryParams, headerParams map[string]param) param {
	if pathParams[name] {
		return param{GoName: name, GoType: goType, Source: "path"}
	}
	if qp, ok := queryParams[name]; ok {
		return param{
			GoName:     name,
			GoType:     goType,
			Source:     "query",
			QueryKey:   qp.QueryKey,
			DefaultVal: qp.DefaultVal,
		}
	}
	if hp, ok := headerParams[name]; ok {
		return param{
			GoName:    name,
			GoType:    goType,
			Source:    "header",
			HeaderKey: hp.HeaderKey,
		}
	}
	return param{GoName: name, GoType: goType, Source: "body"}
}

func extractReturns(fn *ast.FuncDecl) []string {
	if fn.Type.Results == nil {
		return nil
	}
	var ret []string
	for _, field := range fn.Type.Results.List {
		ts := exprToString(field.Type)
		if len(field.Names) == 0 {
			ret = append(ret, ts)
		} else {
			for range field.Names {
				ret = append(ret, ts)
			}
		}
	}
	return ret
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ArrayType:
		return "[]" + exprToString(t.Elt)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// --- OpenAPI 3.0 spec generation ---

type oaSpec struct {
	OpenAPI string                     `json:"openapi"`
	Info    oaInfo                     `json:"info"`
	Paths   map[string]map[string]oaOp `json:"paths"`
}

type oaInfo struct {
	Title   string `json:"title"`
	Version string `json:"version"`
}

type oaOp struct {
	OperationID string            `json:"operationId"`
	Tags        []string          `json:"tags,omitempty"`
	Parameters  []oaParam         `json:"parameters,omitempty"`
	RequestBody *oaReqBody        `json:"requestBody,omitempty"`
	Responses   map[string]oaResp `json:"responses"`
}

type oaParam struct {
	Name     string   `json:"name"`
	In       string   `json:"in"`
	Required bool     `json:"required"`
	Schema   oaSchema `json:"schema"`
}

type oaReqBody struct {
	Required bool                   `json:"required"`
	Content  map[string]oaMediaType `json:"content"`
}

type oaMediaType struct {
	Schema oaSchema `json:"schema"`
}

type oaResp struct {
	Description string                 `json:"description"`
	Content     map[string]oaMediaType `json:"content,omitempty"`
}

type oaSchema struct {
	Type   string    `json:"type,omitempty"`
	Format string    `json:"format,omitempty"`
	Items  *oaSchema `json:"items,omitempty"`
	Ref    string    `json:"$ref,omitempty"`
}

func goTypeToSchema(goType string) oaSchema {
	t := strings.TrimPrefix(goType, "*")
	if elem, ok := strings.CutPrefix(t, "[]"); ok {
		inner := goTypeToSchema(elem)
		return oaSchema{Type: "array", Items: &inner}
	}
	switch t {
	case "string":
		return oaSchema{Type: "string"}
	case "int", "int32":
		return oaSchema{Type: "integer", Format: "int32"}
	case "int64":
		return oaSchema{Type: "integer", Format: "int64"}
	case "float32":
		return oaSchema{Type: "number", Format: "float"}
	case "float64":
		return oaSchema{Type: "number", Format: "double"}
	case "bool":
		return oaSchema{Type: "boolean"}
	default:
		// qualified type like simulator.SimContext -> #/components/schemas/SimContext
		name := t
		if i := strings.LastIndex(t, "."); i >= 0 {
			name = t[i+1:]
		}
		return oaSchema{Ref: "#/components/schemas/" + name}
	}
}

func tagForPath(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "/api/v1/"), "/")
	if len(parts) == 0 {
		return "default"
	}
	return parts[0]
}

func buildOpenAPISpec(routes []route) oaSpec {
	spec := oaSpec{
		OpenAPI: "3.0.3",
		Info: oaInfo{
			Title:   "PainScaler API",
			Version: "1.0.0",
		},
		Paths: map[string]map[string]oaOp{},
	}

	for _, r := range routes {
		op := oaOp{
			OperationID: r.FuncName,
			Tags:        []string{tagForPath(r.RoutePath)},
			Responses:   map[string]oaResp{},
		}

		for _, p := range r.Params {
			switch p.Source {
			case "path":
				op.Parameters = append(op.Parameters, oaParam{
					Name:     p.GoName,
					In:       "path",
					Required: true,
					Schema:   goTypeToSchema(p.GoType),
				})
			case "query":
				op.Parameters = append(op.Parameters, oaParam{
					Name:     p.QueryKey,
					In:       "query",
					Required: p.DefaultVal == "",
					Schema:   goTypeToSchema(p.GoType),
				})
			case "header":
				op.Parameters = append(op.Parameters, oaParam{
					Name:     p.HeaderKey,
					In:       "header",
					Required: false,
					Schema:   goTypeToSchema(p.GoType),
				})
			case "body":
				op.RequestBody = &oaReqBody{
					Required: true,
					Content: map[string]oaMediaType{
						"application/json": {Schema: goTypeToSchema(p.GoType)},
					},
				}
			}
		}

		// determine response schema from return types
		hasResult := (len(r.Returns) > 1) || (len(r.Returns) == 1 && r.Returns[0] != "error")
		hasError := len(r.Returns) > 0 && r.Returns[len(r.Returns)-1] == "error"

		if hasResult {
			retType := r.Returns[0]
			schema := goTypeToSchema(retType)
			op.Responses["200"] = oaResp{
				Description: "OK",
				Content: map[string]oaMediaType{
					"application/json": {Schema: schema},
				},
			}
		} else {
			op.Responses["204"] = oaResp{Description: "No Content"}
		}

		if hasError {
			op.Responses["500"] = oaResp{
				Description: "Internal Server Error",
				Content: map[string]oaMediaType{
					"application/json": {Schema: oaSchema{Ref: "#/components/schemas/Error"}},
				},
			}
		}

		// use the original {param} path converted to OpenAPI {param} style (already correct)
		path := r.RoutePath
		if spec.Paths[path] == nil {
			spec.Paths[path] = map[string]oaOp{}
		}
		spec.Paths[path][strings.ToLower(r.Method)] = op
	}

	return spec
}

// oaSpecWithComponents wraps oaSpec to include components in the JSON output.
type oaSpecWithComponents struct {
	OpenAPI    string                     `json:"openapi"`
	Info       oaInfo                     `json:"info"`
	Paths      map[string]map[string]oaOp `json:"paths"`
	Components oaComponents               `json:"components"`
}

type oaComponents struct {
	Schemas map[string]oaSchema `json:"schemas"`
}

func buildOpenAPISpecJSON(routes []route) ([]byte, error) {
	base := buildOpenAPISpec(routes)

	// collect all referenced schemas
	refs := map[string]bool{}
	collectRefs(base, refs)

	schemas := map[string]oaSchema{
		"Error": {Type: "object"},
	}
	for name := range refs {
		if name == "Error" {
			continue
		}
		schemas[name] = oaSchema{Type: "object"}
	}

	full := oaSpecWithComponents{
		OpenAPI: base.OpenAPI,
		Info:    base.Info,
		Paths:   base.Paths,
		Components: oaComponents{
			Schemas: schemas,
		},
	}

	return json.MarshalIndent(full, "", "  ")
}

func collectRefs(spec oaSpec, refs map[string]bool) {
	for _, methods := range spec.Paths {
		for _, op := range methods {
			for _, p := range op.Parameters {
				collectSchemaRefs(p.Schema, refs)
			}
			if op.RequestBody != nil {
				for _, mt := range op.RequestBody.Content {
					collectSchemaRefs(mt.Schema, refs)
				}
			}
			for _, resp := range op.Responses {
				for _, mt := range resp.Content {
					collectSchemaRefs(mt.Schema, refs)
				}
			}
		}
	}
}

func collectSchemaRefs(s oaSchema, refs map[string]bool) {
	if s.Ref != "" {
		name := s.Ref[strings.LastIndex(s.Ref, "/")+1:]
		refs[name] = true
	}
	if s.Items != nil {
		collectSchemaRefs(*s.Items, refs)
	}
}
